### ISSUE TITLE
OS viewer display names and column headers

### ISSUE THREAD

**Issue by Victordeleon** [openspending/os-data-importers#4]
Is there any way to control OS viewer tags and differentiate them from the downloadable csv column headers?

For example, the filter tags are the same than de data base headers:

![image](https://cloud.githubusercontent.com/assets/17733942/20691196/f1733a10-b594-11e6-8c18-8048342752a5.png)

Is there any way to choose a name for the display names in the OS viewer and another one for the downloadable data base headers?

**Comment by akariv** [comment]
Hey @Victordeleon , you can add a `title` property to each of the headers (beside the `options` and the `osType` properties), which should be the display name of the field.
It should not affect the downloadable CSV file.
