### ISSUE TITLE
Data set and data base names

### ISSUE THREAD

**Issue by Victordeleon** [openspending/os-data-importers#5]
@akariv I've made a new pull request, but I still have some doubts so I would like to ask:

How can I change the data set name (I only found the data set title).
How can I change the downloadable csv file's title.

It would be good if we could differntiate the data set title, data set name and data base name, so we could try different data sets and use the same name without overwriting them.

**Comment by akariv** [comment]
I've added the two optional properties `dataset-name` and `resource-name` you can now specify besides `title`.
If not specified, `dataset-name` will be deduced from the title and `resource-name` will be deduced from the dataset name.
